rm(list=ls())
library(ff)
library(compiler)
enableJIT(3)
gc()
dados <- read.csv.ffdf(file='C:/Users/Gustavo/Desktop/microdados/DADOS/DADOS_ENEM_2012.csv', header=T, sep=',', VERBOSE=T, next.rows=500000, colClasses=NA)
#dados <- read.csv.ffdf(file='dados.csv', header=T, sep=',', VERBOSE=T, next.rows=500000, colClasses=NA)
d
dados$NU_INSCRICAO <- NULL
dados$NU_ANO <- NULL
dados$COD_MUNICIPIO_RESIDENCIA <- NULL
dados$NO_MUNICIPIO_RESIDENCIA <- NULL
dados$COD_UF_RESIDENCIA <- NULL
dados$UF_RESIDENCIA <- NULL
dados$IN_ESTUDA_CLASSE_HOSPITALAR <- NULL
dados$COD_ESCOLA <- NULL
dados$COD_MUNICIPIO_ESC <- NULL
dados$NO_MUNICIPIO_ESC <- NULL
dados$COD_UF_ESC <- NULL
dados$UF_ESC <- NULL
dados$ID_DEPENDENCIA_ADM_ESC <- NULL
dados$ID_LOCALIZACAO_ESC <- NULL
dados$SIT_FUNC_ESC <- NULL
dados$IDADE <- NULL
dados$TP_SEXO <- NULL
dados$NACIONALIDADE <- NULL
dados$COD_MUNICIPIO_NASCIMENTO <- NULL
dados$NO_MUNICIPIO_NASCIMENTO <- NULL
dados$COD_UF_NASCIMENTO <- NULL
dados$UF_NASCIMENTO <- NULL
dados$ST_CONCLUSAO <- NULL
dados$ANO_CONCLUIU <- NULL
dados$TP_ESCOLA <- NULL
dados$IN_TP_ENSINO <- NULL
dados$TP_ESTADO_CIVIL <- NULL
dados$TP_COR_RACA <- NULL
dados$IN_BAIXA_VISAO <- NULL
dados$IN_CEGUEIRA <- NULL
dados$IN_SURDEZ <- NULL
dados$IN_DEFICIENCIA_AUDITIVA <- NULL
dados$IN_SURDO_CEGUEIRA <- NULL
dados$IN_DEFICIENCIA_FISICA <- NULL
dados$IN_DEFICIENCIA_MENTAL <- NULL
dados$IN_DEFICIT_ATENCAO <- NULL
dados$IN_DISLEXIA <- NULL
dados$IN_GESTANTE <- NULL
dados$IN_LACTANTE <- NULL
dados$IN_IDOSO <- NULL
dados$IN_AUTISMO <- NULL
dados$IN_SABATISTA <- NULL
dados$IN_BRAILLE <- NULL
dados$IN_AMPLIADA_24 <- NULL
dados$IN_AMPLIADA_18 <- NULL
dados$IN_LEDOR <- NULL
dados$IN_ACESSO <- NULL
dados$IN_TRANSCRICAO <- NULL
dados$IN_LIBRAS <- NULL
dados$IN_LEITURA_LABIAL <- NULL
dados$IN_MESA_CADEIRA_RODAS <- NULL
dados$IN_MESA_CADEIRA_SEPARADA <- NULL
dados$IN_APOIO_PERNA <- NULL
dados$IN_GUIA_INTERPRETE <- NULL
dados$IN_CERTIFICADO <- NULL
dados$NO_ENTIDADE_CERTIFICACAO <- NULL
dados$COD_UF_ENTIDADE_CERTIFICACAO <- NULL
dados$UF_ENTIDADE_CERTIFICACAO <- NULL
dados$COD_MUNICIPIO_PROVA <- NULL
dados$NO_MUNICIPIO_PROVA <- NULL
dados$COD_UF_PROVA <- NULL
dados$UF_PROVA <- NULL
dados$NOTA_CN <- NULL
dados$NOTA_CH <- NULL
dados$NOTA_LC <- NULL
dados$NOTA_MT <- NULL
dados$NU_NOTA_COMP1 <- NULL
dados$NU_NOTA_COMP2 <- NULL
dados$NU_NOTA_COMP3 <- NULL
dados$NU_NOTA_COMP4 <- NULL
dados$NU_NOTA_COMP5 <- NULL
dados$IN_STATUS_REDACAO <- NULL
dados$NU_NOTA_REDACAO <- NULL
dados$Q001 <- NULL
dados$Q002 <- NULL
dados$Q003 <- NULL
dados$Q004 <- NULL
dados$Q005 <- NULL
dados$Q006 <- NULL
dados$Q007 <- NULL
dados$Q008 <- NULL
dados$Q010 <- NULL
dados$Q011 <- NULL
dados$Q012 <- NULL
dados$Q013 <- NULL
dados$Q014 <- NULL
dados$Q015 <- NULL
dados$Q016 <- NULL
dados$Q017 <- NULL
dados$Q018 <- NULL
dados$Q019 <- NULL
dados$Q020 <- NULL
dados$Q021 <- NULL
dados$Q022 <- NULL
dados$Q023 <- NULL
dados$Q024 <- NULL
dados$Q025 <- NULL
dados$Q026 <- NULL
dados$Q027 <- NULL
dados$Q028 <- NULL
dados$Q029 <- NULL
dados$Q030 <- NULL
dados$Q031 <- NULL
dados$Q032 <- NULL
dados$Q033 <- NULL
dados$Q034 <- NULL
dados$Q035 <- NULL
dados$Q036 <- NULL
dados$Q037 <- NULL
dados$Q038 <- NULL
dados$Q039 <- NULL
dados$Q040 <- NULL
dados$Q041 <- NULL
dados$Q042 <- NULL
dados$Q043 <- NULL
dados$Q044 <- NULL
dados$Q045 <- NULL
dados$Q046 <- NULL
dados$Q047 <- NULL
dados$Q048 <- NULL
dados$Q049 <- NULL
dados$Q050 <- NULL
dados$Q051 <- NULL
dados$Q052 <- NULL
dados$Q053 <- NULL
dados$Q054 <- NULL
dados$Q055 <- NULL
dados$Q056 <- NULL
dados$Q057 <- NULL
dados$Q058 <- NULL
dados$Q059 <- NULL
dados$Q060 <- NULL
dados$Q061 <- NULL
dados$Q062 <- NULL
dados$Q063 <- NULL
dados$Q064 <- NULL
dados$Q065 <- NULL
dados$Q066 <- NULL
dados$Q067 <- NULL
dados$Q068 <- NULL
dados$Q069 <- NULL
dados$Q070 <- NULL
dados$Q071 <- NULL
dados$Q072 <- NULL
dados$Q073 <- NULL
dados$Q074 <- NULL
dados$Q075 <- NULL
dados$Q076 <- NULL
dados$Q077 <- NULL
dados$Q078 <- NULL
dados$Q079 <- NULL
dados$Q080 <- NULL
dados$Q081 <- NULL
dados$Q082 <- NULL
dados$Q083 <- NULL
dados$Q084 <- NULL
dados$Q085 <- NULL
dados$Q086 <- NULL
dados$CO_MUNICIPIO_RESIDENCIA <- NULL
dados$CO_UF_RESIDENCIA <- NULL
dados$SG_UF_RESIDENCIA <- NULL
dados$IN_TREINEIRO <- NULL
dados$CO_ESCOLA <- NULL
dados$CO_MUNICIPIO_ESC <- NULL
dados$CO_UF_ESC <- NULL
dados$SG_UF_ESC <- NULL
dados$TP_DEPENDENCIA_ADM_ESC <- NULL
dados$TP_LOCALIZACAO_ESC <- NULL
dados$TP_SIT_FUNC_ESC <- NULL
dados$NU_IDADE <- NULL
dados$TP_NACIONALIDADE <- NULL
dados$CO_MUNICIPIO_NASCIMENTO <- NULL
dados$CO_UF_NASCIMENTO <- NULL
dados$SG_UF_NASCIMENTO <- NULL
dados$TP_ST_CONCLUSAO <- NULL
dados$TP_ANO_CONCLUIU <- NULL
dados$TP_ENSINO <- NULL
dados$IN_DISCALCULIA <- NULL
dados$IN_VISAO_MONOCULAR <- NULL
dados$IN_OUTRA_DEF <- NULL
dados$IN_SEM_RECURSO <- NULL
dados$IN_NOME_SOCIAL <- NULL
dados$IN_MACA <- NULL 
dados$IN_COMPUTADOR <- NULL
dados$IN_CADEIRA_ESPECIAL <- NULL
dados$IN_CADEIRA_CANHOTO <- NULL
dados$IN_CADEIRA_ACOLCHOADA <- NULL
dados$IN_PROVA_DEITADO <- NULL
dados$IN_MOBILIARIO_OBESO <- NULL
dados$IN_LAMINA_OVERLAY <- NULL
dados$IN_PROTETOR_AURICULAR <- NULL
dados$IN_MEDIDOR_GLICOSE <- NULL
dados$IN_MAQUINA_BRAILE <- NULL
dados$IN_SOROBAN <- NULL
dados$IN_MARCA_PASSO <- NULL
dados$IN_SONDA <- NULL
dados$IN_MEDICAMENTOS <- NULL
dados$IN_SALA_INDIVIDUAL <- NULL
dados$IN_SALA_ESPECIAL <- NULL
dados$IN_SALA_ACOMPANHANTE <- NULL
dados$IN_MOBILIARIO_ESPECIFICO <- NULL
dados$IN_MATERIAL_ESPECÍFICO <- NULL
dados$CO_UF_ENTIDADE_CERTIFICACAO <- NULL
dados$SG_UF_ENTIDADE_CERTIFICACAO <- NULL

dados$SG_UF_PROVA <- NULL
dados$CO_MUNICIPIO_PROVA<- NULL
dados$CO_UF_PROVA <- NULL
dados$Q009 <- NULL
dados$NU_NOTA_CN <- NULL
dados$NU_NOTA_CH <- NULL
dados$NU_NOTA_LC <- NULL
dados$NU_NOTA_MT <- NULL
dados$COD_MUNICIPIO_INSC <- NULL
dados$NO_MUNICIPIO_INSC <- NULL
dados$UF_INSC <- NULL
dados$IN_UNIDADE_HOSPITALAR <- NULL
dados$IN_AMPLIADA <- NULL
dados$PK_COD_ENTIDADE <- NULL
dados$ID_DEPENDENCIA_ADM <- NULL
dados$ID_LOCALIZACAO <- NULL
dados$SIT_FUNC <- NULL
dados$UF_MUNICIPIO_PROVA <- NULL
dados$NU_NT_CN <- NULL
dados$NU_NT_CH <- NULL
dados$NU_NT_LC <- NULL
dados$NU_NT_MT <- NULL



write.csv(dados,file="dados_2012.csv")



